# Generated by Django 4.2.4 on 2023-10-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistema', '0004_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajos',
            old_name='nombre',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='trabajos',
            old_name='plataforma',
            new_name='oficina',
        ),
        migrations.AddField(
            model_name='compras',
            name='proveedor',
            field=models.CharField(default='proveedor', max_length=50),
        ),
        migrations.AddField(
            model_name='trabajos',
            name='equipo',
            field=models.CharField(default='PC', max_length=50),
        ),
        migrations.AddField(
            model_name='trabajos',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trabajos',
            name='fecha_termino',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trabajos',
            name='personal',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
