# Generated by Django 4.2.4 on 2023-10-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistema', '0005_rename_nombre_trabajos_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='proveedor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='equipo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
